Error1		   db 'Invalid function number',13,10,0
Error2		   db 'File not found',13,10,0
Error3		   db 'Path not found',13,10,0
Error4		   db 'Too many open files',13,10,0
Error5		   db 'Access denied',13,10,0
Error6		   db 'Invalid handle',13,10,0
Error7		   db 'Memory control blocks destroyed',13,10,0
Error8		   db 'Insufficient memory',13,10,'$'
Error9		   db 'Invalid memory block address',13,10,0
Error10 	   db 'Invalid environment',13,10,0
Error11 	   db 'Invalid format',13,10,0
Error12 	   db 'Invalid access code',13,10,0
Error13 	   db 'Invalid data',13,10,0
Error14 	   db 'Reserved',13,10,0
Error15 	   db 'Invalid drive specified',13,10,0
Error17 	   db 'Not the same device',13,10,0
Error80 	   db 'File already exists',13,10,0
Error0feh	   db 'Must be .txt or .asm file',13,10,0
ErrorFF 	   db 'Unknown Error, hex code = ',13,10,0