;=======================================================================;
;                                                                       ;
;                       File handle Table                               ;
;                                                                       ;
;=======================================================================;
Filehandle:
FileHandle0			rb      32	
FileHandle1			rb      32        
FileHandle2			rb      32
FileHandle3			rb      32
FileHandle4			rb      32
FileHandle5			rb      32
FileHandle6			rb      32
FileHandle7			rb      32
FileHandle8			rb      32
FileHandle9			rb      32
FileHandle10			rb      32
FileHandle11			rb      32
FileHandle12			rb      32
FileHandle13			rb      32
FileHandle14			rb      32
FileHandle15			rb      32
FileHandle16			rb      32
FileHandle17			rb      32
FileHandle18			rb      32
FileHandle19			rb      32
FileHandle20			rb      32
;====================================================;
;  Space to grow                                     ;
;====================================================;
JustInCase              rb       512 * 4        



