;=========================================================;
; RTL8139 Vendor and Device ID's                 05/12/08 ;
;---------------------------------------------------------;
; Add any new vendor/device ID in here and inc ID Count   ;
;                                                         ;
;=========================================================;
DeviceVendorID:
dd  0x813910ec
dd  0x813810ec
dd  0x12111113
dd  0x13601500
dd  0x13604033
dd  0x13001186
dd  0x13401186
dd  0xab0613d1
dd  0xa1171259
dd  0xa11e1259
dd  0xab0614ea
dd  0xab0714ea
dd  0x123411db
dd  0x91301432
dd  0x101202ac
dd  0x0106018a
dd  0x1211126c
dd  0x81391743
dd  0x8139021b